AllCops:
  TargetRubyVersion: '3.1.3'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Metrics/BlockLength:
  Exclude: 
    - '**/tasks/**/*.rake'

Metrics/MethodLength:
  Max: 20 # goal is 10

Metrics/ClassLength:
  Max: 200 # goal is 100

Metrics/AbcSize:
  Max: 40 # goal is 17!

Layout/LineLength:
  Max: 120



