version: "3"
services:
  db:
    image: postgres:14
    shm_size: 1g
    volumes:
      - ./tmp/storage/postgres:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      env_file: .env
