version: "3"
services:
  db:
    image: postgres:14
    shm_size: 1g
    volumes:
      - ./tmp/storage/postgres:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "8085:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    env_file:
      - ".env"
  meilisearch:
    image: getmeili/meilisearch:v0.29
    ports:
      - "7772:7700"
    volumes:
      - ./tmp/storage/meilisearch:/tmp/meilisearch
    env_file:
      - ".env.sample"
      - ".env"